services:
    allower:
        image: allower:latest
        environment:
            IPINFO_TOKEN: ${IPINFO_TOKEN:-}
        volumes:
            - ./test-data:/data
            - ./config.yaml:/config.yaml
