services:
    allower:
        image: allower:latest
        build:
            context: .
            dockerfile: Dockerfile
        container_name: allower
        ports:
            - 1024:1024 # Tihi
            - 5201:5201
            - 6060:6060
        networks:
            - demo-net
        environment:
            IPINFO_TOKEN: ${IPINFO_TOKEN:-}
            LOG_PRETTY: false
            LOG_LEVEL: "info"
            METRICS: 30s
        volumes:
            - ./test-data:/persist
    demo:
        image: nginxdemos/hello
        container_name: demo-site
        networks:
            - demo-net
    iperf3:
        image: iperf3-server:latest
        build:
            context: ./iperf3-server
        container_name: iperf3-server
        networks:
            - demo-net

networks:
    demo-net:
        driver: bridge
